intermediat revision - added showing stages titles to window title

diff --git a/integration/Vagrantfile b/integration/Vagrantfile
--- a/integration/Vagrantfile
+++ b/integration/Vagrantfile
@@ -7,13 +7,20 @@
 require 'yaml'
 require 'pp'
 
-basedir = ENV.fetch('USERPROFILE', '')
-basedir = ENV.fetch('HOME', '') if basedir == ''
-basedir = basedir.gsub('\\', '/')
+basedir = ENV.fetch('HOME', ENV.fetch('USERPROFILE', '') ).gsub('\\', '/')
 debug = ENV.fetch('DEBUG', false)
 debug =  true if debug =~ /^(?:true|yes|1)$/i
+# e.g. export MANIFEST='dummy.pp'
+manifest = ENV.fetch('MANIFEST','default.pp')
 
+if debug
+  puts "basedir = \"#{basedir}\""
+end
 dir = File.expand_path(File.dirname(__FILE__))
+
+# TODO: inspect the ENV.fetch('SHELL', '')
+TITLE = 'VAGRANTFILE'
+puts "\e]0;#{TITLE}\a"
 
 # NOTE: to solve trouble with NLS ACP like cyrillic, patch the bootstrap script
 # e.g. for Vagrant 2.0.2, the '/c/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.2/bin/vagrant'
@@ -76,7 +83,6 @@ Vagrant.configure('2') do |config|
     image_filename = box_config[:image_filename]
     box_url = "file://#{basedir}/Downloads/#{image_filename}"
     config.vm.synced_folder './' , '/vagrant'
-    manifest = 'default.pp'
     config.vm.define box_name do |guest|
       guest.vm.box = box_config[:image_name]
       guest.vm.box_url = box_url
@@ -87,65 +93,79 @@ Vagrant.configure('2') do |config|
       end
       # guest.vm.provision is a recommended scope
       config.vm.provision 'shell', inline: <<-SHELL
+        TITLE='SHELL PROVISION'
+        echo -ne "\\e]0;${TITLE}\\a"
+
         sudo yum install -y vim
-    UPGRADE_PUPPET=false
-    # optionally upgrade puppet to the latest version
-    if $UPGRADE_PUPPET ; then
-      sudo rpm -Uvh https://yum.puppet.com/puppet5/puppet5-release-el-7.noarch.rpm
-      sudo yum install -y puppet-agent
-    fi
-	# https://www.digitalocean.com/community/tutorials/how-to-install-apache-tomcat-7-on-centos-7-via-yum
-	# change locale of the base image
-cat<<EOF>/etc/environment
-LANG=en_US.utf-8
-LC_ALL=en_US.utf-8
+        UPGRADE_PUPPET=false
+        # optionally upgrade puppet to the latest version
+        if $UPGRADE_PUPPET ; then
+          sudo rpm -Uvh https://yum.puppet.com/puppet5/puppet5-release-el-7.noarch.rpm
+          sudo yum install -y puppet-agent
+        fi
+        # https://www.digitalocean.com/community/tutorials/how-to-install-apache-tomcat-7-on-centos-7-via-yum
+        # change locale of the base image
+        # NOTE: should have no indentation
+        cat<<EOF>/etc/environment
+        LANG=en_US.utf-8
+        LC_ALL=en_US.utf-8
 EOF
-MODULE_PATH='#{modulepath}'
-# set to true - need stdlib 4.25+
-DIRECT_INSTALL_PUPPET_MODULES=true
+        MODULE_PATH='#{modulepath}'
+        # set to true - need stdlib 4.25+
+        DIRECT_INSTALL_PUPPET_MODULES=true
 
-if $DIRECT_INSTALL_PUPPET_MODULES ; then
-  if [ ! -d ${MODULE_PATH}/stdlib ]; then
-    puppet module install 'puppetlabs-stdlib' --version '4.25.0' --target-dir $MODULE_PATH
-    puppet module install 'puppetlabs-java' --version '1.3.0' --target-dir $MODULE_PATH
-  fi
+        if $DIRECT_INSTALL_PUPPET_MODULES ; then
+          if [ ! -d ${MODULE_PATH}/stdlib ]; then
+            puppet module install 'puppetlabs-stdlib' --version '4.25.0' --target-dir $MODULE_PATH
+            puppet module install 'puppetlabs-java' --version '1.3.0' --target-dir $MODULE_PATH
+          fi
 
-  # for encrypted yaml
-  # gem install hiera-eyaml --no-rdoc --no-ri
-fi
-sudo yum install -q -y httpd
-# for integration testing
-sudo yum install -q -y java-1.8.0-openjdk
-# install tomcat 8.5.x via direct download
-# based on: https://www.howtoforge.com/tutorial/how-to-install-tomcat-on-centos/#step-install-apache-tomcat-
-sudo groupadd tomcat
-sudo useradd -s /bin/false -g tomcat -d /opt/tomcat tomcat
-# TOMCAT_VERSION='8.5.30'
-TOMCAT_VERSION='8.5.39'
-# https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.39/bin/apache-tomcat-8.5.39.tar.gz
-TOMCAT_PACKAGE="https://archive.apache.org/dist/tomcat/tomcat-8/v${TOMCAT_VERSION}/bin/apache-tomcat-${TOMCAT_VERSION}.tar.gz"
-sudo mkdir -p /opt/tomcat
-pushd /opt
-if wget --spider $TOMCAT_PACKAGE >/dev/null 2>&1 ; then
-  # NOTE: Invalid progress type ‘none’.
-  sudo wget -O apache-tomcat-8.5.tar.gz $TOMCAT_PACKAGE >/dev/null 2>&1
-fi
-sudo tar xzf /opt/apache-tomcat-8.5.tar.gz
-sudo mv apache-tomcat-${TOMCAT_VERSION}/* tomcat/
-sudo rmdir apache-tomcat-${TOMCAt_VERSION}/* tomcat/
-sudo chown -hR tomcat:tomcat tomcat
-popd
+          # for encrypted yaml
+          # gem install hiera-eyaml --no-rdoc --no-ri
+        fi
+        sudo yum install -q -y httpd
+        # for integration testing
+        # sudo yum install -q -y java-1.8.0-openjdk
+        sudo yum install java-11-openjdk java-11-openjdk-devel
+        sudo yum erase -q java-1.8.0-openjdk java-1.8.0-openjdk-headless
+        java -version 2>&1 | grep -q '11.'
+        if [ $? -ne 0 ] ; then
+          echo 'Failed to erase Java 1.8'
+        fi
+        # install tomcat 8.5.x via direct download
+        # based on: https://www.howtoforge.com/tutorial/how-to-install-tomcat-on-centos/#step-install-apache-tomcat-
+        sudo groupadd tomcat
+        sudo useradd -s /bin/false -g tomcat -d /opt/tomcat tomcat
+        # TOMCAT_VERSION='8.5.30'
+        TOMCAT_VERSION='8.5.39'
+        # https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.39/bin/apache-tomcat-8.5.39.tar.gz
+        TOMCAT_PACKAGE="https://archive.apache.org/dist/tomcat/tomcat-8/v${TOMCAT_VERSION}/bin/apache-tomcat-${TOMCAT_VERSION}.tar.gz"
+        sudo mkdir -p /opt/tomcat
+        pushd /opt
+        if wget --spider $TOMCAT_PACKAGE >/dev/null 2>&1 ; then
+          # NOTE: Invalid progress type ‘none’.
+          sudo wget -O apache-tomcat-8.5.tar.gz $TOMCAT_PACKAGE >/dev/null 2>&1
+        fi
+        sudo tar xzf /opt/apache-tomcat-8.5.tar.gz
+        sudo mv apache-tomcat-${TOMCAT_VERSION}/* tomcat/
+        sudo rmdir apache-tomcat-${TOMCAt_VERSION}/* tomcat/
+        sudo chown -hR tomcat:tomcat tomcat
+        popd
 
-# prerequisite for vanilla puppetlabs-mysql https://github.com/puppetlabs/puppetlabs-mysql
-sudo yum erase -q -y mariadb-libs mariadb
-rpm -qa | grep -i percona | xargs -i sudo yum erase -q -y {}
-# for puppet testing install jq
-sudo yum install -q -y jq
-    SHELL
+        # prerequisite for vanilla puppetlabs-mysql https://github.com/puppetlabs/puppetlabs-mysql
+        sudo yum erase -q -y mariadb-libs mariadb
+        rpm -qa | grep -i percona | xargs -i sudo yum erase -q -y {}
+        # for puppet testing install jq
+        sudo yum install -q -y jq
+      SHELL
       # workaround for older Vagrant / Puppet 4 compatibility issue
       # NOTE: hiera arguments not set
       # config.vm.provision 'shell', inline: "puppet apply --modulepath=#{modulepath}:/vagrant/modules /vagrant/manifests/#{manifest}"
-
+      # NOTE: TITLE is not 100% reliable -
+      # when multiple phases changing ne another the wrong one may end up being shown in window title
+      # after being cached previously
+      TITLE = "PUPPET PROVISION #{manifest}"
+      puts "\e]0;#{TITLE}\a"
       config.vm.provision :puppet do |puppet|
         puppet.hiera_config_path = 'hiera.yaml'
         puppet.module_path       = 'modules'
@@ -153,6 +173,7 @@ sudo yum install -q -y jq
         puppet.manifest_file     = manifest
         puppet.options           = "--verbose --modulepath #{modulepath}:/vagrant/modules "
         puppet.working_directory = '/tmp/vagrant-puppet'
+        #
         config.vm.synced_folder 'hieradata/', '/tmp/vagrant-puppet/hieradata'
       end
       # based on: https://github.com/andrewwardrobe/PuppetIntegration/blob/master/Vagrantfile
@@ -161,14 +182,17 @@ sudo yum install -q -y jq
       # urugeas: http://mirror.nodesdirect.com/centos/7.7.1908/sclo/x86_64/rh/rh-ruby23/rh-ruby23-2.2-7.el7.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found
 
       config.vm.provision 'shell', inline: <<-EOF
+        TITLE='SERVERSPEC'
+        echo -ne "\\e]0;${TITLE}\\a"
         ENABLE_SCL_RUBY=false
+        # currently SCL_RUBY is broken
         if [ $ENABLE_SCL_RUBY  = 'true' ]; then
           echo Checking prerequisites for running rspec
           export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${SCL_BASE_PATH}/usr/lib64
-  	RUBY_VERSION='2.4'
-  	RUBY_VERSION_SUFFIX='24'
+          RUBY_VERSION='2.4'
+          RUBY_VERSION_SUFFIX='24'
           SCL_BASE_PATH="/opt/rh/rh-ruby${RUBY_VERSION_SUFFIX}/root"
-  	ruby --version | grep -q " ${RUBY_VERSION}."
+          ruby --version | grep -q " ${RUBY_VERSION}."
           if [ $? == 0 ] ; then
             echo "Ruby ${RUBY_VERSION}.x is installed"
           else
@@ -191,8 +215,8 @@ sudo yum install -q -y jq
           echo Done
           echo Running spec
           cd /vagrant/local_test
-  	export DEBUG=#{debug}
-  	echo "Set DEBUG=${DEBUG}"
+          export DEBUG=#{debug}
+          echo "Set DEBUG=${DEBUG}"
           rake spec
         fi
       EOF
